server {
    listen 8081;
    location / {
        proxy_pass https://maas-llm-aiplatform-hcm.api.vngcloud.vn;
        proxy_set_header Host maas-llm-aiplatform-hcm.api.vngcloud.vn;
        proxy_set_header Authorization $http_authorization;
        proxy_set_header Content-Type $http_content_type;
        proxy_ssl_server_name on;
        proxy_ssl_name maas-llm-aiplatform-hcm.api.vngcloud.vn;
        proxy_connect_timeout 60s;
        proxy_read_timeout 120s;
    }
}
